coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080

# Giới hạn tài nguyên (tùy máy)
query.max-memory=4GB
query.max-memory-per-node=1GB
memory.heap-headroom-per-node=1GB

discovery-server.enabled=true
discovery.uri=http://trino:8080

node.environment=de-bootcamp
node.id=trino-coordinator-1
node.data-dir=/var/trino/data
